services:
  redis:
    image: redis:latest
    container_name: practice-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./data:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

